import { Amy, Andrew, Chris, Ciro, Gemma, Kery, Ratings } from "../assets";

export const PEOPLES = [
	{
		id: 1,
		name: "Amy",
		pic: Amy,
		expertise: "expertise",
		experience: "10 years",
		location: "India",
		sales: "+200%",
		ratings: Ratings,
	},
	{
		id: 2,
		name: "Andrew",
		pic: Andrew,
		expertise: "expertise",
		experience: "10 years",
		location: "India",
		sales: "+200%",
		ratings: Ratings,
	},
	{
		id: 3,
		name: "Chris",
		pic: Chris,
		expertise: "expertise",
		experience: "10 years",
		location: "India",
		sales: "+200%",
		ratings: Ratings,
	},
	{
		id: 4,
		name: "Ciro",
		pic: Ciro,
		expertise: "expertise",
		experience: "10 years",
		location: "India",
		sales: "+200%",
		ratings: Ratings,
	},
	{
		id: 5,
		name: "Gemma",
		pic: Gemma,
		expertise: "expertise",
		experience: "10 years",
		location: "India",
		sales: "+200%",
		ratings: Ratings,
	},
	{
		id: 6,
		name: "Kery",
		pic: Kery,
		expertise: "expertise",
		experience: "10 years",
		location: "India",
		sales: "+200%",
		ratings: Ratings,
	},
];
